#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_SUNWAVE_FINGERPRINT) += sunwave/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_CHIPONE_FINGERPRINT) += chipone/
